- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "imu_data"
  gz_topic_name: "/imu_data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "altimeter_data"
  gz_topic_name: "/altimeter_data"
  ros_type_name: "ros_gz_interfaces/msg/Altimeter"
  gz_type_name: "gz.msgs.Altimeter"
  direction: GZ_TO_ROS

- ros_topic_name: "contact_data"
  gz_topic_name: "/contact_data"
  ros_type_name: "ros_gz_interfaces/msg/Contacts"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS

