controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - thigh_to_shank
      - body_to_rw_left
      - body_to_rw_right
    interfaces:
      - position
      - velocity

effort_controller:
  ros__parameters:
    joints:
      - thigh_to_shank
      - body_to_rw_left
      - body_to_rw_right
